### ISSUE TITLE
Streaming message feature

### ISSUE THREAD

**Issue by HassenMabrouki** [xmtp/example-chat-react-native#2] opened 2022-11-16 11:30 UTC
# Context 
Attempting to use xmtp-js in React Native, I successfully integrate the SDK, I can send messages, and also get the messages list works fine.
# Problem
Listen for new messages in a conversation it's not working
```
for await (const message of await conversation.streamMessages()) {
  if (message.senderAddress === xmtp.address) {
    // This message was sent from me
    continue
  }
  console.log(`New message from ${message.senderAddress}: ${message.content}`)
}
````
# Screenshot
![Screen Shot 2022-11-16 at 12 11 51 PM](https://user-images.githubusercontent.com/95028333/202165574-f8184c9f-47d0-44eb-8c5a-837e6bdfbf7d.png)
<img width="568" alt="Screen Shot 2022-11-16 at 12 14 23 PM" src="https://user-images.githubusercontent.com/95028333/202166029-c57d9562-0943-4887-9920-099cfeb9290c.png">
# Expectation
As I followed the documentation, the expected result whenever I send a message from user A to user B, the message should be displayed for user B, but it is not the case for me.

I'll be so thankful If give us any hints to make this work. :)

**Comment by elisealix22** [comment] 2022-12-02 20:20
Duplicate of https://github.com/xmtp/xmtp-js/issues/223

**Closed by elisealix22** 2022-12-02 20:20 UTC
